### ISSUE TITLE
Gerrit incremental mode is not working when process is interrupted

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-perceval#229]
Current Gerrit data collection gets data from newest to oldest so if the process is restarted there is no way to know whether there is a gap with changesets to be retrieved. This error leads us to bizarre scenarios, where the #op guys have to check whether gerrit is running or not before stopping a container.

Not having a gerrit data collection that supports to be restarted without having everything collected is something we must fix

**Comment by sduenas** [comment]
In gerrit is not possible to retrieve items from `oldest` to `newest`. As far as I know, the gerrit interface doesn't provide that option. That's why `has_resuming` is set to `False` for this backend.

The only chance to return items in that order is to fetch all items first and then, return them backwards. But in most of the cases this is not possible because memory restrictions, among other problems.
