### ISSUE TITLE
How to parse perceval output into valid JSON?

### ISSUE THREAD

**Issue by brylie** [chaoss/grimoirelab-perceval#28]
The output of the `perceval git` command does not appear to be valid JSON. Rather, it is a series of objects, that are not comma delimeted:

``` js
{
    "Author": "Ville Jyrkk\u00e4 <ville.jyrkka@samposoftware.com>",
    "AuthorDate": "Mon Feb 22 10:54:58 2016 +0200",
    "Commit": "Ville Jyrkk\u00e4 <ville.jyrkka@samposoftware.com>",
    "CommitDate": "Mon Feb 22 10:54:58 2016 +0200",
    "__metadata__": {
        "backend_name": "Git",
        "backend_version": "0.1.0",
        "origin": "https://github.com/Digipalvelutehdas/dipor-dashboard.git",
        "timestamp": 1458733054.514615,
        "updated_on": 1456131298.0,
        "uuid": "60208b4c67b862b7f5d34b913d179fc827e8814c"
    },
    "commit": "752192d16eee70cdbaf6e6fe2feba20e4ed8cb4f",
    "files": [
        {
            "action": "A",
            "added": "2",
            "file": "README.md",
            "indexes": [
                "0000000...",
                "1fe1d4e..."
            ],
            "modes": [
                "000000",
                "100644"
            ],
            "removed": "0"
        }
    ],
    "message": "Initial commit",
    "parents": [],
    "refs": []
}
{
    "Author": "Brylie Christopher Oxley <brylie@gnumedia.org>",
    "AuthorDate": "Mon Feb 22 11:40:37 2016 +0200",
    "Commit": "Brylie Christopher Oxley <brylie@gnumedia.org>",
    "CommitDate": "Mon Feb 22 11:40:37 2016 +0200",
    "__metadata__": {
        "backend_name": "Git",
        "backend_version": "0.1.0",
        "origin": "https://github.com/Digipalvelutehdas/dipor-dashboard.git",
        "timestamp": 1458733054.515244,
        "updated_on": 1456134037.0,
        "uuid": "0cd185cadcbcd8d588a79cc4fef7cab54579ce6c"
    },
    "commit": "709723c75e11069626496007a442d119a168c560",
    "files": [
        {
            "action": "A",
            "added": "116",
            "file": "docs/LICENSE",
            "indexes": [
                "0000000...",
                "670154e..."
            ],
            "modes": [
                "000000",
                "100644"
            ],
            "removed": "0"
        }
    ],
    "message": "Initial migration",
    "parents": [
        "752192d16eee70cdbaf6e6fe2feba20e4ed8cb4f"
    ],
    "refs": []
}
...
```

How can we convert this output into valid JSON?

**Comment by brylie** [comment]
Our goal is to get this data into a JavaScript visualization framework or MongoDB document database, so valid JSON would be useful in the former case.

**Comment by sduenas** [comment]
Perceval does not produce a JSON object. It generates a set of valid JSON objects. One JSON document per item.

We decided to follow this behaviour because Perceval does not wait to fetch and parse all the bugs - in your case - from a repository to return them. In some repositories, it can last hours. For this reason, as soon as it fetches and parses an item, it returns it into a valid JSON document.

To parse it you can do something like this:
```python
#!/usr/bin/env python3

import json
import sys

parsed = []
buffer = None

for line in sys.stdin.readlines():
    if line.startswith('{\n'):
        buffer = line
    elif line.startswith('}\n'):
        buffer += line
        obj = json.loads(buffer)
        parsed.append(obj)
    else:
        buffer += line

for i in parsed:
    print(i)
    # Do whatever with the parsed item
```

And then read the output from Perceval with:
```
perceval git 'https://github.com/grimoirelab/perceval.git' --from-date '2016-03-10' | ./read_json.py
```
**Note**: I coded it fast so it might be buggy

**Comment by brylie** [comment]
Is there a script/example for streaming Perceval output into a JSON file or database?

**Comment by acs** [comment]
I this use case you have samples for bugzilla and git using the p2o tool:

https://github.com/grimoirelab/use_cases/blob/master/documentfoundation/README.md#41-bugzilla

**Comment by jgbarah** [comment]
@brylie Can we close this, or do you need further explanations?

**Comment by brylie** [comment]
@jgbarah it is OK to close. However, this could be treated as a feature request. E.g. there could be a `perceval --toJSON` flag that, when used, writes a valid JSON file to disk, or that can be piped to another program

**Comment by jgbarah** [comment]
I see. OK, I'm tagging this as "enhacement". @sduenas @acs what do you think? I could write the code, it is not that difficult, even for me ;-) And I agree that could be an interesting feature.

**Comment by vchrombie** [comment]
@jgbarah 
Is this work still pending?

I found this issue as a good way to start tweaking the code and learn more about Perceval.

**Comment by valeriocos** [comment]
I'm not sure that producing a JSON doc that includes all items retrieved by Perceval can be a good solution when mining large repositories (https://github.com/torvalds/linux), since the JSON obtained may not fit in memory. Currently perceval provides the feature [--json-line](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backend.py#L325), which produces a JSON line for each output item. Thus, if the output is piped to a file, one just needs to iterate over the file line by line and load the JSON content.

If you agree, I would close this issue @sduenas @jgbarah .

**Comment by sduenas** [comment]
Yeah, that's the point about not having a long document. The solutions are either use `--json-line` flag or parse the output as I described [here](https://github.com/chaoss/grimoirelab-perceval/issues/28#issuecomment-200330136),
