### ISSUE TITLE
Allow git backend to clone using ssh keys instead of http Basic Auth

### ISSUE THREAD

**Issue by filmaj** [chaoss/grimoirelab-perceval#398]
My company's git backend uses GitHub Enterprise behind an SSO authentication scheme, so HTTP Basic Auth is not an option. We can only clone repositories using SSH keys.

I think this would need to be a new feature for perceval.

I am happy to take a stab at putting together this feature in a PR, but could use some guidance. My company and I deploy GrimoireLab internally using the `full` docker image. I imagine Mordred would also need updates to be able to specify the location of the SSH key to use when cloning (via one of its configurations?).

**Comment by sduenas** [comment]
To clone a repository Perceval runs `git clone` in a subprocess. One way to support SSH would be to use [dulwich](https://github.com/dulwich/dulwich) library instead. I think it can work with SSH keys. Perceval already uses `dulwich` in some parts of the git backend, so it would be easy to support it.

Another option would be a mix of `GIT_ASKPASS` [environment variable](https://git-scm.com/book/gr/v2/Git-Internals-Environment-Variables) and [Credential Storage](https://git-scm.com/book/gr/v2/Git-Tools-Credential-Storage#_credential_caching).

We would be more than happy to support this feature. We haven't found time to implement it so far.

**Comment by jgbarah** [comment]
This is related to chaoss/grimoirelab-sirmordred#165 isn't it? (just to have a cross-reference).

**Comment by filmaj** [comment]
@jgbarah yes, I believe so!

**Comment by filmaj** [comment]
It looks like by a) having the SSH keys in place appropriately and b) using the git@git / ssh URL for the project, I am able to get perceval to pull git commits properly.

So possibly this issue could just be a documentation one, making the above info explicit.

**Comment by filmaj** [comment]
oh and also binding an ssh `known_hosts` file into the container was needed :)

**Comment by cewilliams** [comment]
Example of what I had to do add to my image start script to implement @filmaj 's comments:
```
    -v /home/<userid>/.ssh/grimoire_ro:/home/grimoirelab/.ssh/id_rsa \
    -v /home/<userid>/.ssh/grimoire_ro.pub:/home/grimoirelab/.ssh/id_rsa.pub \
    -v /home/<userid>/.ssh/known_hosts:/home/grimoirelab/.ssh/known_hosts \
```

The important bit being that the key file names in the container need to use `id_rsa` instead of whatever you named them when you generated your key. I also created the .ssh directory in an earlier container layer before binding the keys in, not sure if this binding works without that manual step.

Also note: **You are saving a very sensitive key in a layer of the docker image**. This can then be picked up by anyone with access to the same machine and used for anything the key has access to, so be sure you mean to share that key and that it doesn't have access to more than you want it to.
