### ISSUE TITLE
Gather data from Pagure

### ISSUE THREAD

**Issue by abitrolly** [chaoss/grimoirelab-perceval#416]
https://pagure.io/ is an open source issue tracker with Git integration, PRs, stats and other features. Would be nice to extract my own data from it for tracking activity.

**Comment by valeriocos** [comment]
hi @abitrolly, thank you for your interest in this project! I like your proposal!
would you like to try to implement the backend? it could be a nice first contribution :)

**Comment by abitrolly** [comment]
In depends. :) I want to extract my daily trail. Perceval seem to dump all available data, which may put too much load on some systems if run daily. Is there a tool that can only follow myself? To track my first contribution. )

**Comment by valeriocos** [comment]
Grimoirelab platform allows to monitor your daily contribution (and much more). For instance, if you have a look to [this Git dashboard](https://opnfv.biterg.io/app/kibana#/dashboard/Git?_g=()) from one of our clients and click on any of the authors, you will see that the visualizations will show just the contributions of that author. If this solution doesn't fit with your needs, you can make a script to daily execute Perceval on the pagure.io repositories you contribute to (and then filter the data you are interested in).
In both cases, you can count on me for both questions about how to proceed or help in coding :)

Note that Perceval can be used in incremental mode (e.g., extracting issues modified after a given date), thus it should not imply too much load on the pagure.io API.

**Comment by Algogator** [comment]
I'd like to pitch in :)

**Comment by propol** [comment]
Greetings!
I'd be interested to try to implement Pagure's backend if possible :)
As I understand I will be using the abstract class for backends available, correct?

**Comment by valeriocos** [comment]
Great, thank you @propol !
Yes, you can have a look at the other [backends](https://github.com/chaoss/grimoirelab-perceval/tree/master/perceval/backends) to see some examples. Feel free to open a PR, and we can iterate over it.

**Comment by propol** [comment]
Sure, will do when I have some code to show for it :) 
Thank you

**Comment by PrajwalM2212** [comment]
I would like to work on this

**Comment by valeriocos** [comment]
that's great, @PrajwalM2212 ! 

Please have a look at https://github.com/inishchith/chaoss-microtasks/tree/master/microtask-1 and https://github.com/chaoss/grimoirelab-sirmordred#setting-up-a-pycharm-dev-environment to set up a dev environment.

Thanks

**Comment by animeshk08** [comment]
Hi!! @valeriocos As no updates have been there on this issue for a while can I work on it.

**Comment by valeriocos** [comment]
Hi @animeshk08 , thank you for your interest in this issue. 

It would be great if you can work on this issue. As references, you can rely on the gitlab and github backends. Feel free to open a pull request linked to this issue, so we can help you with the implementation.

Categories are the types of the data we can extract from a backend. They are generally defined based on some business needs/scenarios. For instance, if we focus on the data we can extract from a Git repository, possible categories could be commits, branches and tags. Commit is the current and only category available for the Git backend. We implemented it because we needed to calculate commit-based metrics (e.g., number of commits per author, weekday when a commit was created). ATM we don't have any scenario targeting git branches or tags, thus we don't need any of other category for Git.

Another example is the data we extract from Gitlab. In this case, our need was to define metrics around issues and merge requests, thus we created 2 categories in the Gitlab backend to fetch these infos.

WRT the backend for Pagure, we can start by fetching the issues for a given project. Other data available through the API can be the target of future backend improvements.

Let me know if you have any doubts, thanks.

**Comment by animeshk08** [comment]
Thank you @valeriocos for the detailed clarification.

**Comment by valeriocos** [comment]
Great @animeshk08 !

> 1. The issue ...

Are the comments returned by the Pagure API for a given issue paginated (i.e., only the first X are returned and we need to iterate on the different pages)? If this is the case, it makes sense to have the comments in a different attribute (comments_data), since the backend/client will have some code to fetch the whole set of comments.

Reactions and comments_data don't have a prori direct deps with other components. However the connectors in ELK will be written based on the strucute of the documents returned by Perceval.

> 2. Some repositories ...

If an API endpoint contains the info about the issue tracker enable/disable, the backend could query this endpoint at the very beginning and return an ad-hoc warning message if needed. Another option is to handle this exception when fetching issues. 

Tomorrow I can have a look at the Pagure API and give you a more detailed feedback.

**Comment by animeshk08** [comment]
Thank you for the fast reply @valeriocos . 
>Are the comments returned by the Pagure API for a given issue paginated
To the best of my understanding the comments are not paginated. However, a given comment object is returned as below
```
{
                "comment": "This is comment 21",
                "date_created": "1583167920",
                "edited_on": null,
                "editor": null,
                "id": 629814,
                "notification": false,
                "parent": null,
                "reactions": {},
                "user": {
                    "fullname": "Animesh Kumar",
                    "name": "animeshk08"
                }
            }
```
As you can see there is no `user_data` key present in this object. So it still may be considered to either edit the same or create a `comment_data` key to accommodate `user_data` in it; if that level of depth is needed. Whichever, implementation do you think is best.
>If an API endpoint contains the info about the issue tracker enable/disable
To the best of my understanding there no API lets us know about this information. Hence we should go for the latter approach.

Please have a look at the following Pagure API documentation and correct me if I am wrong [here](https://pagure.io/api/0/)

**Comment by valeriocos** [comment]
Yes, you are right @animeshk08! The pagination seems to exist only for issues.

> As you can see there is no user_data key present in this object. So it still may be considered to either edit the same comment key or create a comment_data key to accommodate user_data in it; if that level of depth is needed. Whichever, implementation do you think is best.

I would not add any `*_data` attribute, since the user information is already included in the comment. Generally the attributes `*_data` contain data extracted from a specific endpoint. For instance, if we focus on GitHub, the comments_data: https://github.com/chaoss/grimoirelab-perceval/blob/fe3b3a3632177b7b61fb382cd8f0ab8e8c50b7f4/perceval/backends/core/github.py#L380 relies on:
- the comments endpoint: https://github.com/chaoss/grimoirelab-perceval/blob/fe3b3a3632177b7b61fb382cd8f0ab8e8c50b7f4/perceval/backends/core/github.py#L651)
- the user endpoint: https://github.com/chaoss/grimoirelab-perceval/blob/fe3b3a3632177b7b61fb382cd8f0ab8e8c50b7f4/perceval/backends/core/github.py#L529

> To the best of my understanding there no API lets us know about this information. Hence we should go for the latter approach.

Perfect (I didn't find any info in the API either)!
