### ISSUE TITLE
Time to fetch issues via GitHub() is very high

### ISSUE THREAD

**Issue by musman-ashraf** [chaoss/grimoirelab-perceval#458]
I need to fetch issues via Github() from multiple repos, however, after fetching few issues it takes way to much time to fetch next ones.

**Comment by valeriocos** [comment]
Are you using an access token (https://github.com/settings/tokens)? Generally if you use an access token you should have plenty of requests (5000) per hour, if you don't you have just 60 requests per hour.

**Comment by valeriocos** [comment]
Try to generate an access token and use it with your script. In order to pass the token, please initialize the GitHub backend in the following way:
```
github = GitHub('<the-owner>', <the-'repo>', api_token='<your-token>', sleep_for_rate=True)
```

If you want to get an access token:
- on the top right corner, click on your avatar and then settings ( https://github.com/settings/profile)
- click on developer settings (https://github.com/settings/developers)
- then click on personal access tokens (https://github.com/settings/tokens)
- then click on the button "generate new token"
- write your password and then the name of your token
- tick off the scopes "repo" and "user" and click "generate token"
- finally the hash of the token will appear in the next page, use it as value of `api_token`

Let me know if this solve your issue

**Comment by musman-ashraf** [comment]
It worked perfectly fine with access token. Thanks a million!

**Comment by valeriocos** [comment]
great! I close this issue @musman-ashraf, feel free to reopen it if needed
