### ISSUE TITLE
Perceival Github Returns Pull Request Under Issue Category also

### ISSUE THREAD

**Issue by sarvesh211999** [chaoss/grimoirelab-perceval#493]
The Existing Problem with Perceval is that when running the below command with category **issue** it also fetches the pull request because the github api returns the pull request under issues. 
`$ perceval github --json-line -category issue omegaup omegaup --sleep-for-rate -t a247a6b7d506736da6d653cddc060a96bfbd9cb3 > data_source.json`

For Example:
This is actually a pull request that is returned as issues in Github API
https://api.github.com/repos/omegaup/omegaup/issues/2378

**Comment by valeriocos** [comment]
Hi @sarvesh211999 , thank you for reporting this issue.

As stated in the GitHub API, [every pull request is an issue, but not every issue is a pull request.](https://developer.github.com/v3/pulls/#labels-assignees-and-milestones). Thus, when fetching issues, some PRs are also returned, You can recognize them because they include the attribute 'pull_request'.
When enabling the category 'pull_request', you will see that the JSON docs returned by Perceval include some additional information not present when fetching issues (e.g., review comments and reviewers).

Hope this helps, please comment or feel free to close this issue.

**Comment by sarvesh211999** [comment]
Yeah I know that GitHub API return additional information when  category pull_request is provided and actually that information is the important information and more useful.
So I was thinking to remove this pull request lines when Perceval is call with issue category as it creates a lot of confusion and there is not that much of information.

**Comment by valeriocos** [comment]
Perceval tries to manipulate/modify as less as possible the data returned by the API in order to have kind of one-to-one correspondence with the original data, so the removal you propose can't be added to Perceval.

**Comment by jgbarah** [comment]
> So I was thinking to remove this pull request lines when Perceval is call with issue category as it creates a lot of confusion and there is not that much of information.

As Valerio commented, Perceval just follows the API. It is not an end-user tool. If you come to the GitHub API, and retrieve data, it is reasonable that Perceval gets for you all what GitHub returns for that kind of API. Of course, higher level tools, such as Grimoire-ELK, should tell issues apart from pull requests, so that users are not confused.

I'm closing this, as we don't think is really a bug. Thanks for the discussion, anyway, and for letting us document it here. @valeriocos: maybe it could make sense to add some clarification to the README and/or Perceval help about this? If so, maybe you can open a separate issue, and label it as "good first issue", so that anyone can contribute.

**Comment by valeriocos** [comment]
Sure @jgbarah , just opened an issue: https://github.com/chaoss/grimoirelab-perceval/issues/494
@sarvesh211999 feel free to work on it.

Thanks
