### ISSUE TITLE
Adding google yapf formatter to the repository for better code maintenance.

### ISSUE THREAD

**Issue by harshalmittal4** [chaoss/grimoirelab-perceval#510]
While working on an issue in perceval, this idea appeared.
I propose adding the google yapf formatter to the repository. It will :

- do **initial yapf formatting** of the entire code to conform to the best style guides.

- add **pre-commit formatting**, which would automtically format the code for any commit so that the style is consistent throughout the codebase.

I would be happy working on this, since it would help in code maintenance. Please let me know your views on this :)
@valeriocos, @jgbarah, @sduenas

**Comment by valeriocos** [comment]
Thank you @harshalmittal4 for sharing this idea. I'm not sure about the advantage of including google yapf formatter, since the grimoirelab repos already use flake8 (which enforces style guide) when executing the tests on Travis (https://github.com/chaoss/grimoirelab-perceval/blob/master/.travis.yml#L20).

Any thoughts @sduenas @jgbarah ?

**Comment by harshalmittal4** [comment]
Actually flake8 just highlights the errors, while the idea is to add yapf plugin as a pre-commit hook so it corrects the errors automatically for each commit, while could also do initial code formatting.

**Comment by jgbarah** [comment]
I have to say that I don't have experience working with yapf. But from a working-flow point of view, I think it would be much better that, in case we want to use it, devels run it before committing, than having it run as a pre-commit hook.

From another point of view, I'm not sure we need yapf, or any other formater for that matter. But that's just my view ;-) @sduenas @valeriocos what do you think?

@harshalmittal4, in any case, thanks a lot for raising the discussion.

**Comment by sduenas** [comment]
To be honest, I'd rather not use this by default.

I don't have experience with this tool and I don't want to introduce anything that I don't really know or understand.

I also think it will make developers lazy about their style. I'm not saying we shouldn't improve code style but I don't think this is the way. It's up to every developer to use it or not, but we shouldn't force to use it because I think, it will create worst developers. I'm also taking from my ignorance, so I'm not sure about it, let's close it and we can reconsider it later.

Thanks for your open this issue.

**Comment by harshalmittal4** [comment]
Sure @sduenas, @jgbarah, @valeriocos, thanks for your valuable feedback! Lets put this down for now, can always turn up to this later in case someone feels :slightly_frowning_face:
