### ISSUE TITLE
[github] __get_pull_requested_reviewers error on Github Enterprise

### ISSUE THREAD

**Issue by cewilliams** [chaoss/grimoirelab-perceval#523]
Github returns a dict from _.../pulls/{number}/requested_reviewers_ with `users` and `teams` keys. Github Enterprise returns a plain list of users. This causes 

https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L387

to throw: 

    File ".../lib/python3.7/site-packages/perceval/backends/core/github.py", line 397, in __get_pull_requested_reviewers
    for requested_reviewer in group_requested_reviewers['users']:
    TypeError: list indices must be integers or slices, not str

**Comment by valeriocos** [comment]
Thank you @cewilliams for reporting this issue. 

Since we don't have a GitHub entreprise instance to replicate the error, would be possible to provide some test data like the one here: https://github.com/chaoss/grimoirelab-perceval/blob/master/tests/data/github/github_request_requested_reviewers (maybe adding also team information) ? In this way, we could easily rework the test [test_fetch_pull_enterprise](https://github.com/chaoss/grimoirelab-perceval/blob/master/tests/test_github.py#L1310).

What do you think ?

Thanks

**Comment by cewilliams** [comment]
Will do. I was already planning on submitting a patch - is there an expected way to determine when Perceval is talking to an Enterprise server? The two options I came up with were: 1) Check during GithubClient __init__ for base_url and setting a flag in the object, or 2) just checking if the returned value was a list and creating a dict with the list in it.

Having the client know that it is talking to an Enterprise server would make more sense if there might be other responses that differ from the public api, but would be extra overhead if this is the only instance we ever have to deal with.

**Comment by valeriocos** [comment]
Great @cewilliams ! I would go for option 2) since it seems more like bug* than something wanted. However, I agree with you for option 1) in case there are other responses that differ from the public api.

*The doc [here](https://developer.github.com/enterprise/2.16/v3/enterprise-admin/) says that the enterprise API offers some additional endpoints plus the public ones.
