### ISSUE TITLE
[github] Get information extra information about issues and pull requests

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-perceval#53]
It would be interesting having the following information from GitHub issues and pull requests:
- Comments (who, what, how many, etc.)
- Labels

**Comment by jsmanrique** [comment]
Any insights about how this can be done?

**Comment by sduenas** [comment]
@acs any idea about when we can include this feature?

**Comment by acs** [comment]
@jsmanrique @sduenas we just need to prioritize it. It should not be that hard to implement.

**Comment by jsmanrique** [comment]
ASAP?

**Comment by acs** [comment]
Ok, in the kitchen now waiting for its turn. Stay tuned.

Labels are already included now:

https://github.com/grimoirelab/GrimoireELK/blob/master/tests/data/github.json#L184

**Comment by jsmanrique** [comment]
@acs, when labels info is added?

Still missing comments authors info I think. Correct me if I am wrong

**Comment by acs** [comment]
@jsmanrique comments are not included yet in the enriched index. 

About the labels, taking a look to the github enricher:

https://github.com/grimoirelab/GrimoireELK/blob/master/grimoire_elk/elk/github.py#L323

The labels are included in this field.

**Comment by jsmanrique** [comment]
AFAIK the number of 'comments' are part of raw data. I suppose each time you ask for the raw data, you get the latest number of comments for each issue.

I think we are mixing raw data extraction and data enrichment.

**Comment by acs** [comment]
I am always talking about the enriched data. In the raw data I am not sure if the comments for each issue/pr are included, or we need to add an extra step to collect this information and include it in the raw data.

**Comment by jsmanrique** [comment]
Yes, that's something to discuss, but it might be interesting, at least, to know:
* people opening issues/pr (already included)
* people commenting issues/pr (not done yet)
* number of comments by each person in each issue/pr

**Comment by valeriocos** [comment]
Hi @acs @jsmanrique @sduenas 
GitHub includes different kinds of comment somehow related to an issue. The way to fetch them (all together or separately) is something that should be discussed.

For instance if you look at #120, you will see that:
issue comments are at https://api.github.com/repos/grimoirelab/perceval/issues/120/comments
review comments are at https://api.github.com/repos/grimoirelab/perceval/pulls/120/reviews
commit comments are at https://api.github.com/repos/grimoirelab/perceval/pulls/120/comments

**Comment by valeriocos** [comment]
The github backend is now able to fetch issue comment data (see PR #152)

**Comment by valeriocos** [comment]
As reported by the GitHub API every pull request is an issue, but not all issues are pull requests (PRs), 
In terms of the API this means that:
- If one opens a bug, the corresponding issue in the API won't have any pull request data until a PR is created for that bug.
- If one sends a PR, the API will create an issue, which will have the pull request data included.

I see two possible solutions to extract pull request data (feel free to add your proposals).
- Treat issues and PRs separately. This means that perceval will be able to fetch two categories of data (issue and PR). When asking perceval to get issues, it will retrieve any issue (including those ones that are PRs) and it will inflate its data with only issue comments and corresponding reactions.
If one asks perceval to get pull requests, only the pull request data within the issue will be retrieved, that data will be then inflated with review comments, requested reviewers and corresponding reactions.

- Treat issues and PRs together. This means that perceval will have just one category (issue), perceval will inflate the issue with data about issue comments and their reactions, and where possible also with PR data (review comments, etc.).

Advantages of the first solution are basically the drawbacks of the second solution and viceversa.

Advantages:
- Save token usage, since PR data will retrieved only if explicitly asked.
- Issue and PR data can evolve separately.

Drawbacks:

- When doing some analysis (e.g., life-cycle of a bug from the initial discussion to its fix), the issue and PR data must be linked together.
- Risk of having issues not in sync with the corresponding pull requests (e.g., updating issue data, but forgetting to update PR data)

I would go for the first solution. What do you think @sduenas @jsmanrique @acs ?

**Comment by jgbarah** [comment]
It's difficult for me to figure out scenarlos where people want to have issues and not prs, or viceversa, since they are so intimately intertangled in GitHub.

I would go for the first scenario only if:

* There no or little penalty when you want both issues and prs (since that would be the most common case)
* You're not losing any info, such as prs related to an issue, or issues related to a pr.

From my understanding, this seems to be the case, so, if that's that way, no problem in going with the first solution.

**Comment by valeriocos** [comment]
A PR with the proposed implementation is available at https://github.com/chaoss/grimoirelab-perceval/pull/172
