### ISSUE TITLE
Data of different versions

### ISSUE THREAD

**Issue by propol** [chaoss/grimoirelab-perceval#532]
Greetings! In case I want to construct an analysis about the history of one project based on its past releases, is there a way to gather the data of  only specific versions (tags) of a github repo through Perceval?

**Comment by valeriocos** [comment]
Hi @propol ,
unfortunately Perceval doesn't provide this info, since there is no direct link between issues and releases in GitHub (afaik). However you could modify Perceval to fetch issues / pull requests based on:
- the start and end dates of a release (if you can obtain them)  
- their tags/labels (if they follow some naming convention for releases)

If you have an example of repo you would like to analyze, I can have a look at it and help you to modify Perceval.

**Comment by propol** [comment]
Thank you for the quick response @valeriocos ,
let's say I want to analyze the versions of a big repo like Laravel: https://github.com/laravel/framework .
I believe I would prefer the first solution you gave as it was something I was thinking of my own because I saw that Perceval supports the --from-date argument (only missing an end-date I suppose, if I have understood correctly) and because various repositories might use different naming conventions for their tags and it wouldn't be very practical of me to modify Perceval differently every time.

Thank you, also, for you help in the matter :)

**Comment by valeriocos** [comment]
You're welcome @propol and thank you for sharing an example of the repo you want to analyze :) I agree with you wrt the first solution.

Please, note that the github backend includes also the `to_date` param:
https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L133

Feel free to close the issue, thanks!

**Comment by propol** [comment]
Oh I see, I'll make sure to look into it! 

Closing the issue, thank you again @valeriocos for your help :)
