### ISSUE TITLE
[feature-request] Fetch events for issues

### ISSUE THREAD

**Issue by Polaris000** [chaoss/grimoirelab-perceval#563]
Apart from the information fetched for issues (`<api_url>/issues/<issue_num>`), it may be a good idea to also fetch event information, or atleast the last re-open event for issues (`<api_url>/issues/<issue_num>/events`). 
Apart from the `created_at`, `closed_at` and `updated_at` fields, there could be an `events` field added to the issue data Perceval fetches.

Though I couldn't find any call to the `events` url in the github backend module, please let me know if this feature already exists.

Currently, when reopened issues are fetched by Perceval, the `status` field is `open` but there is a `closed_by` field as well. That could be one way to tell which issues were reopened, but how do you find the date of reopening?

Thanks in advance @valeriocos , @sduenas!

**Comment by valeriocos** [comment]
Hi @Polaris000 , a PR addressing your request has been just made available.
I noticed some inconsistency in the documentation at: https://developer.github.com/v3/activity/events/#list-public-events. In particular, it is reported that:
```
Events support pagination, however the per_page option is unsupported. The fixed 
page size is 30 items. Fetching up to ten pages is supported, for a total of 300 events.

Only events created within the past 90 days will be included in timelines. Events older 
than 90 days will not be included (even if the total number of events in the timeline is 
less than 300).
``` 

However from the tests I did (fetching events from grimoirelab-perceval repo), I was able to fetch events that happened before 90 days ago. Since you are going to use the code in the PR, could you provide some feedback?

Thanks

**Comment by Polaris000** [comment]
I'll have a look, thanks @valeriocos.

**Comment by sduenas** [comment]
As I said in #565, we'll keep this on hold until there's a solution that doesn't break Perceval.
