### ISSUE TITLE
How to set IP address for perceval github issue

### ISSUE THREAD

**Issue by Julianbaozi** [chaoss/grimoirelab-perceval#663]
To avoid sending too many requests for one IP address, can I set different IP aliases to fetch github issue? I'm doing these tasks in multithreads, so I also want to fetch data with different IPs at the same time.

**Comment by valeriocos** [comment]
Hi @Julianbaozi , I'm not sure that this can be handled by Perceval (or by other GrimoireLab components). Using a proxy could be a solution to explore, otherwise you could either split the target repos in different servers (which have different IPs) or reduce the number of tasks running in parallel.

**Comment by sduenas** [comment]
Not sure if I understand your question right but if you want to use different IPs that would depend on your network configuration. You will need to have available those public IP addresses, just because you have different net interfaces or because the router you connect to go outside has those IPs. In both cases, you will have to configure your routing system to do that and decide which interface it will use. If you are under a private local network, only your router with different IPs would do that.

Also, instead of multi-threading, you can always use [arthur](https://github.com/chaoss/grimoirelab-kingarthur). You can define different workers in different machines so they will use different IP addresses. Remember if you are under a private network, this won't help you either unless your router does something different.

**Comment by Julianbaozi** [comment]
Can i use Arthur in sirmordred? When using arthur, how many workers can
there be on one machine?

**Comment by valeriocos** [comment]
> Can i use Arthur in sirmordred?

The current version of Mordred doesn't support Arthur. Please have a look at this previous answer:
https://github.com/chaoss/grimoirelab-sirmordred/issues/462#issuecomment-622957274. You can find more details on https://github.com/chaoss/grimoirelab/issues/299

> When using arthur, how many workers can
there be on one machine?

There is no constraint on the number of workers. AFAIK no evaluation has been conducted to assess this number.

**Comment by Julianbaozi** [comment]
Here I mean, Arthur can help me multi process on my on laptop right?

**Comment by valeriocos** [comment]
If you mean `having multiple executions of Perceval running at the same time`, the answer is yes.

Arthur is a scheduler of Perceval jobs, which are managed using a queue-based approach. The workers constantly check the queues, take the jobs and process them.

**Comment by valeriocos** [comment]
@Julianbaozi let's close this issue, feel free to reopen it if needed, thanks.
