### ISSUE TITLE
First Date

### ISSUE THREAD

**Issue by Julianbaozi** [chaoss/grimoirelab-perceval#666]
How to get the date of the first commit or the date of creation of a repository without fetching all data?

**Comment by vchrombie** [comment]
Hi @Julianbaozi 

I think it is not really possible to get the date without fetching all the data. 

You have to fetch the whole data using perceval and you need to iterate over the JSON documents to find the first commit date or you can use GitHub API too if you don't need any data to be downloaded. 

Also, sometimes the date of creation of a repository and the first commit might be different too. I can create an empty repository and push commits after an year. ^^

I hope it helps.

**Comment by Julianbaozi** [comment]
The creation date of Openssl/openssl is 2013 but the first commit is 1998..
why is that?

**Comment by vchrombie** [comment]
> The creation date of Openssl/openssl is 2013 but the first commit is 1998.. why is that?

I am not really sure but I think there is a possibility of that case too. Maybe they were using some other software earlier such as GitLab or phabricator before creating the GitHub repository.

**Comment by valeriocos** [comment]
Hi @Julianbaozi ,

> The creation date of Openssl/openssl is 2013 but the first commit is 1998..
why is that?

This probably due to the fact that the repo was imported to GitHub in 2013. Thus, the creation date in GitHub is 2013, but the repo was started in 1998.

I don't think Git explicitly models the creation date of a repository. If you want to rely only on Git data, you could consider the repo creation date as the date of the first commit. An option to explore could be to look for the date when some files (e.g., description, info) in the folder .git were created, however this option doesn't seem reliable (ref: https://stackoverflow.com/questions/25689294/how-to-get-the-date-of-git-repository-init).

If you want to use GitHub and Git data, you can assume that the repo creation date is calculated as the function min(first commit, github repo creation date). As suggested by @vchrombie you can use the GitHub API without passing by Perceval.

Thank you @vchrombie for helping with this issue.

**Comment by sduenas** [comment]
There's no way to get a reliable date of when a Git repository was created. Also, the oldest commit doesn't need to be the first commit created because you can remove commits or import others from different places.

Having said that, if what you want is to get the first commit we return in Perceval (usually the first commit in `master` branch) there are several ways to do it. For all of them, you will need to download the whole repository first (either with Perceval or manually). Maybe the best one is to use the code from the [tutorial](https://chaoss.github.io/grimoirelab-tutorial/perceval/git.html#using-perceval-as-a-python-module) and where the code says:

```
for commit in repo.fetch():
    print(commit['data']['commit'])
```

replace it by:

```
for commit in repo.fetch():
    print(commit['date']['CommitDate'])
```

**Comment by Julianbaozi** [comment]
Thank you
