### ISSUE TITLE
perceval git (very) slow on big repo

### ISSUE THREAD

**Issue by gibello** [chaoss/grimoirelab-perceval#674]
Tried perceval git on a big Git repo, but it gets stuck almost forever:

```
perceval git --latest-items https://github.com/xwiki/xwiki-platform
```
When launched on a smaller repo, the same command works fine, so there's an issue related to the repo size.

Note: the doc at https://chaoss.github.io/grimoirelab-tutorial/perceval/git.html states that "To produce this result, Perceval cloned the git repository to analyze, and got information for all its commits” […]" - but  I suppose most stats are retrieved using REST APIs, not cloning ?

**Comment by valeriocos** [comment]
Hi @gibello,

> I suppose most stats are retrieved using REST APIs, not cloning ?

The Git backend [clones](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py#L323) the repo and then queries the [log](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py#L993), there is not interaction with any REST API.

I made 3 tests using the repo https://github.com/xwiki/xwiki-platform, they consisted in
- cloning the repo (git clone https://github.com/xwiki/xwiki-platform)
```
slimbook@slimbook-KATANA:/tmp$ date
vie jun  5 11:48:05 CEST 2020
slimbook@slimbook-KATANA:/tmp$ git clone https://github.com/xwiki/xwiki-platform
Clonando en 'xwiki-platform'...
remote: Enumerating objects: 139, done.
remote: Counting objects: 100% (139/139), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 1175114 (delta 37), reused 92 (delta 17), pack-reused 1174975
Recibiendo objetos: 100% (1175114/1175114), 378.95 MiB | 7.59 MiB/s, listo.
Resolviendo deltas: 100% (554361/554361), listo.
Revisando archivos: 100% (10752/10752), listo.
slimbook@slimbook-KATANA:/tmp$ date
vie jun  5 11:49:21 CEST 2020
slimbook@slimbook-KATANA:/tmp$ 
```

As you can see the repo is pretty large, and the time to clone it is less than **1 minute 20 secs** (my connection is around 40 Mbps)

- running Perceval for the first time on the repo using the command you shared. This implies that Perceval will clone and extract the commits. 
```
[2020-06-05 11:58:54,823] - Sir Perceval is on his quest.
...
[2020-06-05 12:02:29,905] - Fetch process completed: 62335 commits fetched
[2020-06-05 12:02:29,906] - Summary of results

	   Total items: 	62335
	Items produced: 	62335
	 Items skipped: 	0

	Last item UUID: 	89a12a9af57635f180dda95692ed56c8888a4c5c
	Last item date: 	2020-06-05 09:51:05+00:00

	Min. item date: 	2003-12-15 09:13:33+00:00
	Max. item date: 	2020-06-05 09:51:05+00:00

	Min. offset: 	-	Max. offset: 	-	Last offset: 	-


[2020-06-05 12:02:29,906] - Sir Perceval completed his quest.
```
As you can see the time to clone and extract the commits is around **3 minutes 30 secs**

- running Perceval for the second time without the option latest-items on. This implies that Perceval will extract all commits, since the repo has been already cloned. 

```
[2020-06-05 12:03:03,007] - Sir Perceval is on his quest.
[2020-06-05 12:05:01,657] - Fetch process completed: 62335 commits fetched
[2020-06-05 12:05:01,657] - Summary of results

	   Total items: 	62335
	Items produced: 	62335
	 Items skipped: 	0

	Last item UUID: 	89a12a9af57635f180dda95692ed56c8888a4c5c
	Last item date: 	2020-06-05 09:51:05+00:00

	Min. item date: 	2003-12-15 09:13:33+00:00
	Max. item date: 	2020-06-05 09:51:05+00:00

	Min. offset: 	-	Max. offset: 	-	Last offset: 	-


[2020-06-05 12:05:01,657] - Sir Perceval completed his quest.
```
As you can see the time to extract the commits is around **2 minutes**. This result is aligned with the results of the previous tests.

Feel free to close the issue, thanks

**Comment by valeriocos** [comment]
I close this issue @gibello , feel free to reopen it if needed.
