### ISSUE TITLE
Documentation for perceval output formatting

### ISSUE THREAD

**Issue by Alch-Emi** [chaoss/grimoirelab-perceval#737]
Howdy!

I'm working on a third-party backend for perceval-osf, but I can't seem to find much documentation regarding what format the data output by perceval is supposed to be in, both of the command, and of the `Backend.fetch()` method.  I can generally piece together what should be produced by comparing outputs from different backends and reverse-engineering some existing code, but this is probably not the ideal way to learn, and certainly not the easiest.

The most documentation I could find is that `fetch()` is supposed to "[retrieve] items from a repository", returning "a generator of items".  However, this does not give very much information at all to what those items are.

[This comment][1] on issue #719 makes a reference to this issue, but I wanted to create a new issue since #719 is primarily about adding a new backend, and also because Google Season of Docs is (I believe) underway.  If this is unwelcome, I apologize for the inconvenience, and would be happy to close this in favor of #719.

[1]: https://github.com/chaoss/grimoirelab-perceval/issues/719#issuecomment-785210102

**Comment by sduenas** [comment]
Hi, first of all sorry for the lack of documentation. Last year, we thought we were going to improve this part but due to some problems managing the GSoD request, we couldn't do it.  A new GSoD is underway so I hope this time we can have a student collaborating on this topic. In the meantime, I can give you some info.

Items are whatever the datasource stores and we want to retrieve and then analyze. For git, it's commits; for github, it's issues and pull requests; for slack, it's messages, etc. We call this *categories*. A backend can retrieve items of different categories.

Items are returned as JSON documents. The first level of the JSON contains some metadata, such as the backend that generated/retrieved that item (`backend` and `backend_version`), when the item was retrieved (`timestamp`), the url to the repository from it was retrieved (`origin`), its category (`category`) and so on. The full list of fields is in [here](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backend.py#L328).

Every item has an `uuid` that makes it unique from other items. Two items can't have the same `uuid`. The uuid [is generated](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backend.py#L334) using different values an parameters that makes the item unique: the origin and the unique identifier that the item has in the repository. In the case of git, this id is the [hash of the commit](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py#L192) but in the case of github, the id is [the unique identifier of the issue or pull request in the service](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L258).

The original data of each item is under `data` field. Everything you can retrieve from an item goes there. Usually datasources or services have a way to get data in JSON format, if that's the case, the JSON document will go in that field. Sometimes that's not the case (e.g. git, bugzilla) and you will need to convert the data to JSON trying to keep the it as similar as the original source. Check the [git parser](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py#L386) to have an idea.

As a rule of thumb, we also want to retrieve everything associated to these items: comments, reviews, reactions, patches, users, etc. Usually that's information that needs to be added to the original item. We follow the rule of naming those fields inside the original item as `<extra>_data`, where `extra` is the type of the extra information the item will contain, for example, `user_data` for user data.

Whenever is possible, data should be retrieved from oldest to newest using the last modification date (`updated_on` field). The reason is that if the backend fails, you know exactly where it finished, so you can resume the work from there. You will also be able to retrieve the newest data that has been produced since the work was restarted.

I hope this helps!

**Comment by Alch-Emi** [comment]
That's very helpful, thank you!  Good luck getting someone for GSoD!

**Comment by sduenas** [comment]
Thanks. I'm gonna close this issue. I hope we can have better documentation soon.
