### ISSUE TITLE
`max-items` is just used for issues, but not for others

### ISSUE THREAD

**Issue by xiao623** [chaoss/grimoirelab-perceval#755]
https://github.com/chaoss/grimoirelab-perceval/blob/4a65eceb6463f1847af6c6e8e5da6b527f6c30e7/perceval/backends/core/github.py#L731

The value of `max-items` is only used for `issues` method, so what is the point of setting this value?

For example:
https://github.com/chaoss/grimoirelab-perceval/blob/4a65eceb6463f1847af6c6e8e5da6b527f6c30e7/perceval/backends/core/github.py#L711
when we called `https://api.github.com/repos/apache/spark/pulls/27058/comments?per_page=100&direction=asc&sort=updated`, we got `Server Error`.
But if `per_page` is 50, the response is 200.

It should also be used in others methods so that we can set `per_page` what we want.

**Comment by zhquan** [comment]
@xiao623 - `max-items` is used when the category is `issue` or `pull_request` but only in the first level and not in its sublevels as `comments`, `reactions`, etc. That means it will set the `per_page` to `max_items` only to fetch issues or pull requests but for each issue/pull to fetch `comments` the `per_page` is always the same `VPER_PAGE = 100`.

Maybe the value `max-items` should extend to all requests and not only for the first level.

> when we called https://api.github.com/repos/apache/spark/pulls/27058/comments?per_page=100&direction=asc&sort=updated, we got Server Error.
But if per_page is 50, the response is 200.

I agree with @vchrombie that the problem is from the GitHub side

**Comment by xiao623** [comment]
Yes, I agree that the problem is from the Github side, and I ask for help in `GitHub Support Community` : [got-server-error-when-called-api](https://github.community/t/got-server-error-when-called-api-https-api-github-com-repos-apache-spark-pulls-27058-comments-per-page-100/199429)

Before they fix the problem, we need to modify `per_page` in `issue_comments` method.
