### ISSUE TITLE
[mbox] Remove requirement for files to begin with `From `

### ISSUE THREAD

**Issue by altsalt** [chaoss/grimoirelab-perceval#770]
There is a [long stale issue](https://github.com/chaoss/grimoirelab-perceval/issues/20) questioning the mbox backend double parsing certain emails. In that discussion, a [question](https://github.com/chaoss/grimoirelab-perceval/issues/20#issuecomment-198527503) was brought up regarding mbox files that do not follow a pre-assumed format.

I am currently trying to parse an archive from a Sympa backed mailing list. These files do not begin with a `From ` line, but the remainder of the headers seem to be standard. I was able to shim a subset of files into a format that Perceval could ingest by combining the `Reply-to:` and `Date:` headers into a new first line beginning with `From `.

It seems as though there is a better way to detect mbox files, especially when Perceval is being told that there is a directory full of them. Thoughts? Suggestions? Development hours?

I doubt that I have the time or understanding of Perceval to address either of these issues at the moment. Thanks for your attention!

**Comment by sduenas** [comment]
The problem is we use the python standard library to parse the files. The library follows the mbox standard, so if the messages don't follow the standard, the library won't do much.

Also, `From` header is used in the mbox /mailbox format to determine the separation between messages. If the header is not there, the parser won't know when a message ends and a new one starts.

**Comment by sduenas** [comment]
Maybe there are other libraries that can handle messages better but we didn't have time to check them because we never found the problem you have. If you want to look for other solutions, any help is welcomed.
