### ISSUE TITLE
[Feature Request] Add GH Archive Backend

### ISSUE THREAD

**Issue by wmeijer221** [chaoss/grimoirelab-perceval#814]
Recently I have been comparing Perceval's GitHub backend with retrieving data through [GH Archive](https://www.gharchive.org/) and noticed that it's quite a bit faster as you're not rate limited by the GitHub API.
Consequently, I was wondering whether there's an appetite for adding a GH Archive backend into Perceval as this could probably benefit people.

In case you're unfamiliar with the GH Archive, it's an archive of all the different [GitHub Events](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads), so events like placing a comment on an issue or creating pull requests are all stored in there.
A great benefit of using this system is the lack of rate limiting so the whole process is a lot faster, however, the downsides are that you're pulling the entire history of GitHub (i.e., a lot of data) and that all data entries are split up (meaning, that to get all data of, e.g., a pull request, you have to iterate through all events related to that pull request: it's creation, separate comments, reviews, closure etc.), so it would probably be useful to have some kind of aggregation logic in there too.

Would there be an interest in such a backend? And if so, what are the odds of it being integrated into this repository vs. storing it as an extension in another repository?
Thanks!

**Comment by sduenas** [comment]
Hi @wmeijer221,

Yes, we know about GH Archive. In fact, we did some code in the past that retrieved data from there but we never integrated it with `perceval`.

The main problem we found - besides the size of data you mentioned -  is that GH Archive is not reliable in terms of data completeness. When you dig in their data, there are a lot of events that aren't stored. That's why we created the backend `githubql` which retrieves events using GitHub's GraphQL API. This method has also other downsides such as the limit of events that can be retrieved.

Speaking of where to store the backend, now we prefer that people maintain their own backends and, once they are enough mature and maintained, we can integrate them with the core. Our rationale is we aren't many developers and it's hard to maintain a large set of backends over time. In the meantime, we can advertise the backend here and on the GrimoireLab main repository. 

Having said that, it would be great to have a backend to get data from GH Archive. If you have time to work on it, we can guide you when you find problems.

**Comment by wmeijer221** [comment]
Thanks for your quick reply!

I was hoping I could use the archive for my research, but I don't think missing data would do much good for the integrity of the work; it's still useful to get a feel of the data, though...

Was data incompleteness something they found or something you found during testing? I couldn't find anything mentioned about missing data in their docs.

**Comment by sduenas** [comment]
Happy to see if someone finally works on this. I'm closing this ticket.
